## Python/Numpy Workshop

For this workshop you will be learning how to use the python library NumPy, which is heavily depended on when writing scripts for machine learning models, as it makes data processing intuitive.

###### Using Jupyter Notebooks
To run a cell, press shift + enter


In [1]:
# 1. Import the numpy package under the name np. You will need to do this step everytime you want to use NumPy!
# 2. Create a rank 1 array (1D) with values from 1 - 3. Call it Z, and print it. 
# 3. Change the first value of Z to a 5.
# 4. Sort Z, and then print it.
#########################



In [2]:
# 1. create a null array of size 10 called Z.
# 2. Make the 5th value of Z equal to 1
# 3. Print Z
##############################


In [3]:
# Print Z after every step below
# 1. Create a 2 x 2 array with all zeros. Call it Z.
# 2. Make Z = to a 2 x 2 array with all ones
# 3. Make Z = to a 2 x 2 array with all 4's
# 4. Make z = to a 2 x 2 identity matrix
##############################


In [4]:
# 1. Create a rank 2 array (2D) with 3 coloumns that looks like [[0 1 2], [3, 4 ,5]]. Call it Z and print it.
# 2. Print the shape of Z.
# 3. Initialize an array X from values 0 - 5. Print X. Print the Shape of X
# 4. Transform X into a rank 2 array with 3 coloumns. Pritn X. Print the shape of X.
#########################



In [5]:
# 1. Create a 5 x 5 matrix and initialize it with random numbers. Call it X.
# 2. Create a 3 x 3 matrix with values ranging from 0-8. Call it Y.
# 3. Print X and Y:
#########################


In [6]:
# 1. Create Z, a rank one array with range 0 - 9.
# 2. Print out the first 5 values of Z
# 3. Print out the last 5 values of Z (bonus: use negative indexing)
# 4. Print out the middle 4 values of Z
###########################



In [7]:
# 1. Create the following array Z (with rank 4) with shape (4,3).
    # [[1 2 3] 
    #  [4 5 6]
    #  [7 8 9]
    #  [10 11 12]]
# 2. Print the shape of Z
# 3. Use slicing to create a subarray X which consists of the last 2 rows and last 2 coloumns of Z. Print X.
# 4. Change the value of Z at [4, 3] to -100 by modifying X. 
# 5. Print X
# 6. Print Z
##############################



###### The following example is something similar to what you would see when setting up a linear regression model. The data is from the Boston Housing Data Set

In [8]:
#import the Boston data set:
from sklearn.datasets import load_boston
boston = load_boston()

print(boston.DESCR)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [9]:
# Investigate shape of the input data array
data = boston.data
target = boston.target

print(data.shape)
print(target.shape)

num_features = len(boston.feature_names)
num_samples = data.shape[0] # 506 training examples

# 1. Normalize the 'Data' as mean-centered, bounded by 1. This means for each feature in num features,
    # calculate the mean and the max of all of the data for that feature, and then subtract the mean and divide by the max for each data point
    # Hint, use the np.amax() function to find the max data point for a feature.
####################################


(506, 13)
(506,)
